name: deployment_tools_azure_login

label: Azure Login

description: |
  Logs in to your Azure Subscription using device login method. This allows access to your azure
  from this container or environment.


type: python3

labels:
  collection:
    - Kitchen Sink
  output_template: azure_login_output.j2

variables:
  - name: deployment_type
    description: AWS or Azure Deployment Type
    default: azure
    type_hint: hidden

snippets:
  - name: script
    file: ../azure_login.py
    output_type: text
    outputs:
    -   name: azure_accounts_str
        capture_pattern: '[^###]+(?=###[^###]*$)'
    -   name: azure_accounts
        capture_expression: azure_accounts_str | from_json